### ISSUE TITLE
Allow a third party to take on capital lock up costs in PM

### ISSUE THREAD

**Issue by yondonfu** [livepeer/research#19]
In the current iteration of the PM candidate construction, broadcasters must lock up an amount of capital in its reserve that could linearly with the number of recipients on the network. We would like to investigate methods to shift the capital lock up costs away from a broadcaster to a third party. This would increase accessibility for broadcasters and also avoid the need for broadcasters to update their recipient set since the third party is the only entity that needs to keep track of recipients.

One thought is to introduce a hub. To be clear, I don't think this design would work, but I'm writing it down anyway to see if it can spark further thinking.

We have a single hub that maintains its own recipient set commitment which might be updated once per round. The hub maintains a reserve that can cover its entire recipient set commitment so that broadcasters don't have to (since broadcasters are only ever paying the hub). Broadcasters send tickets to the hub and the hub sends tickets to the designated orchestrator (recipient).

In order, to synchronize payments we can use hash timelocks.

- B defines `secret`, `H(secret)` and `b_timeout`
- B creates `enc_secret = E(o_pub_key, secret)`, `secret` encrypted to O's public key
- B sends `H(secret)`, `b_timeout` and `enc_secret` to the hub
- The hub creates `h_timeout` which is less than `b_timeout`
- The hub sends `H(secret)`, `h_timeout` and `enc_secret` to O
- O decrypts `enc_secret` to obtain `secret` and sends it to the hub
- The hub checks that `secret` is the correct hash pre-image and sends a ticket to O
- Since the hub knows `secret`, it sends it to B
- B checks that `secret` is the correct hash pre-image. It knows that the hub would only know `secret` if O revealed it to claim its ticket. So, B sends a ticket to the hub

If O does not reveal `secret` to the hub by `h_timeout`, the hub disconnects from O.
If the hub does not reveal `secret` to B by `b_timeout`, B disconnects from the hub.

This would benefit from non-interactive winning ticket selection so that both B and the hub and create tickets without interaction from the counterparty.

One benefit of this relative to a payment channel hub (based on virtual channels) seems to be that if the hub ever goes down, there is no need for a recipient to have to submit many on-chain transactions in order to close all of its virtual channels. This feels an awful lot like a hash timelock based payment channel hub though - are there any benefits of this relative to that?

That being said, this hub might not be practical since every message needs to be relayed through the hub which can introduce latency issues which can be particularly detrimental in a live video context. This is where virtual channel based hubs are superior to any hash timelock approach (since the hub blocks off funds once and then peers can send payments without hub participation).

**Comment by j0sh** [comment]
Not to bring up off-chain payments again, but hubs would work nicely for extending credit towards broadcasters. Virtual channels are a good fit here; the hub only needs to be consulted once per time-period to ensure B has a line of credit available (eg, a valid CC on file).

How to settle this balance with O is a separate issue (eg, whether to convert to crypto, and when).

**Comment by yondonfu** [comment]
After some discussion we concluded that if you're going to use a hub, you might as well use a payment channel hub as opposed to using PM tickets
