### ISSUE TITLE
Policy Based Verification

### ISSUE THREAD

**Issue by j0sh** [livepeer/research#37]
### Introduction : Broadcaster's Interests

During discussions on verification, it has become apparent that there is a difference in the interests that broadcasters and orchestrators have towards quality and verification, which in turn has significant implications on the approach taken to address those interests.

The broadcaster has an interest in receiving good video, and should expect to continue receiving good video even in the presence of potentially malicious transcoders. Mechanisms to dis-incentivize orchestrator misbehavior (eg, slashing) only indirectly address the broadcaster's interest in good video, may produce outcomes counter to the B's own interests [1], and does not stop an O from mounting an attack if the perceived returns outweigh the cost of such an attack.

Hence, it may be beneficial to think of ways to directly address the broadcaster's interest in good video. @mk-livepeer has also emphasized that the effects of poor-quality or tampered video may have far-reaching effects beyond a single stream, in damage to the perception and confidence of the Livepeer network.

A reputation system ("risk score") for orchestrators can be one aspect of evaluating a trustworthy orchestrator, but is not a complete solution in itself, since it also does not prevent attacks outright. Another potential tool in the mitigation toolbox would be in the use of a "policy algorithm" to select segments with a certain level of quality.

### The Policy Algorithm

To start with, the B can define a policy that dictates the B's local verification behavior based on its risk tolerance. Consider the following algorithm that submits a segment until a required quality score is met, or a certain number of submission attempts have been reached:

```golang
Policy {
  verification_rate  // How often to verify segments, from 0.0 (never) to 1.0 (always)
  score                   // Score that the B generally expects for a segment
  attempts             // Maximum number of retry attempts
}

 // ... segment submission pseudo code ...

Policy P
Segment sourceSegment
Segment bestSegment
int bestScore = 0, attempts = 0

while bestScore < P.score && attempts < P.attempts {
  O = GetOrchestrator()
  results = SubmitSegment(sourceSegment, O)
  score = Verify(sourceSegment, results)
  if score > bestScore {
    bestSegment = results
    bestScore = score
  }
  attempts++
}

InsertIntoPlaylist(bestSegment)
```

If the B uses all `P.attempts` without reaching its `P.score` goal, then it's more likely the segment is a false positive from the verifier. In that case, the B can just use the best-scoring segment of all the attempts. If there's any tampering, *all* orchestrators selected would need to tamper. Otherwise, there only needs to be one honest orchestrator among the set, since we use the one with the highest score. False negatives (eg, letting tampered video through) would only happen if the verification metric assigns a higher score to tampered video.

The quality score should be a continuous metric. Binary classification might still work, but probably requires a using M-of-N ensemble, special consideration needs to be given to false positives [1], and false negatives [2] would be almost impossible to defend against.

[1] False positive: Labelling a honest segment as tampered
[2] False negative: Not labelling a tampered segment

### Redundant  / Parallel Transcoding

If the `P.score` is set too high, or the content is particularly difficult, the B may find itself repeatedly retrying segments in order to get a better quality score. This would be slow. Other than loosening the policy itself, one way to reduce the latency associated with repeated checking is to do all attempts in parallel. The B would simultaneously send segments to `P.attempts` orchestrators for transcoding, and use the first one that responds with `score >= P.score`.

Redundant transcodes also offer a few other approaches for arriving at the best score, other than defining a score via policy. The B could opt for a purely "best-of" approach, where it selects M-of-N and selects the highest scoring result among that set, or gathers all responses up until a timeout. The tradeoff is increased cost, both in transcoding fees and the marginal cost per stream due to the need to simultaneously transmit, receive and verify several streams at once. The "best-of" approaches don't offer the very lowest latency due to waiting for the slowest M transcoders, or a timeout, but may still be quicker than serial attempts.

A randomized approach to selecting orchestrators is recommended for parallel / redundant transcoding, or for retried segments that have failed verification. Selecting solely based on predictable factors such as latency has a higher probability of selecting colluding nodes that may be colocated with one another, as in a Sybil attack.

### Orchestrator Behavior

In this design, the orchestrator does not need to verify its own results or calculate its own metric score. Such a requirement would only come into the picture if the O was at risk of slashing or other punishment. Whether or not to slash (and how) is a separate but complementary topic on de-incentivizing orchestrator behavior, and does not directly address the broadcaster's interest in receiving good video.

This approach also makes no attempt to gauge the correctness of a particular orchestrator's work: it only attempts to maximize a quality score to further the interests of B.

[1] If an O is subject to slashing, verifying all its own segments is mandatory. Not only does this increase latency and cost, the O may refuse to return segments that may trigger a false positive challenge, even if the work was done honestly. Then B has paid for transcoding and received nothing in return.

**Comment by f1l1b0x** [comment]
There is no way we can get around B validating himself

How would you know the P.score the Os are telling you are actually true and not just a fake?
You can not without validating on your own!

The basic principles of trustless networks can not be achieved without a trustless validation method.

Our reputation, SLA and slashing system can be as good as it gets but if O gets hacked you have no control as B unless you have a way to validate the content yourself.

Bs interest is in this priority:

1. tamperproof
2. reliable
3. cost efficient
4. quality
5. low latency

3, 4 and 5 might vary based on the use case.

**Comment by j0sh** [comment]
> How would you know the P.score the Os are telling you are actually true and not just a fake?
You can not without validating on your own!

The B does the validation itself, not the O. The `P.score` is a policy parameter local to B. The O doesn't need to be aware of any of this.

**Comment by f1l1b0x** [comment]
Ah ok sorry I missunderstood.

I thought getting the P.scores is too much of a computational burden for B

what is the cost to create it?

Philipp

**Comment by j0sh** [comment]
The choice of validation method was deliberately left unspecified, because it's not really important for this proposal other than preferably being a continuous metric ("score") rather than a binary classifier. Something like SSIM would work.

**Comment by j0sh** [comment]
Implemented in https://github.com/livepeer/go-livepeer/pull/1096
